name: run-tests
on:
  push:
    branches:
      - "develop"

  pull_request:
    branches:
      - "develop"

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install typescript
        run: npm install -g typescript

      - name: Install dependencies
        run: npm clean-install

      - name: Compile typescript
        run: npm run compile

      - name: Format code
        run: npm run format

      - name: Lint and fix code
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm clean-install

      - name: Install firebase
        run: sudo npm i -g firebase-tools

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Cache JAR files
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators/
          key: emulator-jar-files

      - name: Run tests
        run: npm run test:ci
