name: run-tests
on: 
  push:
    branches:
      - "develop"

  pull_request:
    branches:
      - "develop"  

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  setup-node:
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install typescript
        run: npm install -g typescript
      - name: Install dependencies
        run: npm clean-install

  compile:
    runs-on: ubuntu-latest
    needs: [setup-node, checkout-code]
    steps:
      - name: Compile typescript
        run: npm run compile

  format:
    runs-on: ubuntu-latest
    needs: [setup-node, checkout-code]
    steps:
      - name: Format code
        run: npm run format

  lint:
    runs-on: ubuntu-latest
    needs: [setup-node, checkout-code]
    steps:
      - name: Lint and fix code
        run: npm run lint

  setup-java:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "termurin"

  test:
    runs-on: ubuntu-latest
    needs: [setup-node, setup-java]
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators/
          key: emulator-jar-files
      - name: Run tests
        run: npm run test:verbose